# Generated by Django 3.0.1 on 2020-01-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('background_image', models.URLField(max_length=2500)),
                ('video_url', models.URLField(max_length=2500)),
                ('content', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Categories')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
